### ISSUE TITLE
Implicit vs explicit function type in `progFun`

### ISSUE THREAD

**Issue by conal** [conal/calculating-compilers-agda#2]
https://github.com/conal/calculating-compilers-agda/blob/7e9c98d4ca9c82c24e5fbf127a9a86a4fd7f47c4/Stack.agda#L247-L262

The “≡⟨ cong sf (evalSO-assoc f’ g’) ⟩” line yields an error:

    A × _Z_938 → C × _Z_938 != {Z : Set} → A × Z → C × Z because one is
    an implicit function type and the other is an explicit function type
    when checking that the expression evalSO-assoc f' g' has type
    (λ {Z} → evalStackOps (f' ++ g')) ≡ _y_934

@ahmadsalim Any insights here?

**Comment by ahmadsalim** [comment]
This is one of those funny Agda errors you get when it does not know when to expand or not expand implicit functions correctly. I will see how to fix it.

**Comment by ahmadsalim** [comment]
So it seems that you are trying to show equality of a function with an implicit, so you need to use function extensionality to make it work.
The following works:

```agda
.progFun-comp : ∀ (g : StackProg B C) (f : StackProg A B) → progFun (g ∘c f) ≡ progFun g ∘c progFun f
progFun-comp (sp g') (sp f') =
  begin
    progFun (sp g' ∘c sp f')
  ≡⟨⟩
    progFun (sp (f' ++ g'))
  ≡⟨⟩
    sf (evalStackOps (f' ++ g'))
  ≡⟨ cong sf ( ext-i (evalSO-assoc f' g') ) ⟩
    sf (evalStackOps g' ∘ evalStackOps f')
  ≡⟨⟩
    sf (evalStackOps g' ∘ evalStackOps f')
  ≡⟨⟩
    sf (evalStackOps g') ∘c sf (evalStackOps f')
  ≡⟨⟩
    progFun (sp g') ∘c progFun (sp f')
  ∎
```
where I had postulated at the top:
```agda
postulate
  .ext : ∀ {α β} → Extensionality α β
  .ext-i : ∀ {α β} → ExtensionalityImplicit α β
```

**Comment by ahmadsalim** [comment]
Please note that I have only added `ext-i` to your proof 😄

**Comment by conal** [comment]
Thanks!
